// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "EchoServer.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class EchoServerHandler : virtual public EchoServerIf {
 public:
	 static bool InitEvironment() { 
		 return true;
	 }
  EchoServerHandler() {
    // Your initialization goes here
  }

  void echo(std::string& _return, const std::string& msg) {
	  _return = msg;
  }

};

