/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef AppService_CONSTANTS_H
#define AppService_CONSTANTS_H

#include "AppService_types.h"

namespace onepc {

class AppServiceConstants {
 public:
  AppServiceConstants();

};

extern const AppServiceConstants g_AppService_constants;

} // namespace

#endif
