#ifndef __IEGAD_CONFIG__
#define __IEGAD_CONFIG__


#define IEGAD_OPTION_BOOST  1
#define IEGAD_OPTION_SIGAR  1
#define IEGAD_OPTION_THRIFT 1
#define IEGAD_OPTION_GLOG   1
#define IEGAD_OPTION_CPP11  1
#define IEGAD_OPTION_SSL    1



#endif // __IEGAD_CONFIG__
