// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iegad_app_svr_msg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "iegad_app_svr_msg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* setup_msg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  setup_msg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_iegad_5fapp_5fsvr_5fmsg_2eproto() {
  protobuf_AddDesc_iegad_5fapp_5fsvr_5fmsg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "iegad_app_svr_msg.proto");
  GOOGLE_CHECK(file != NULL);
  setup_msg_descriptor_ = file->message_type(0);
  static const int setup_msg_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(setup_msg, log_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(setup_msg, pwd_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(setup_msg, email_),
  };
  setup_msg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      setup_msg_descriptor_,
      setup_msg::default_instance_,
      setup_msg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(setup_msg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(setup_msg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(setup_msg));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_iegad_5fapp_5fsvr_5fmsg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    setup_msg_descriptor_, &setup_msg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_iegad_5fapp_5fsvr_5fmsg_2eproto() {
  delete setup_msg::default_instance_;
  delete setup_msg_reflection_;
}

void protobuf_AddDesc_iegad_5fapp_5fsvr_5fmsg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027iegad_app_svr_msg.proto\"7\n\tsetup_msg\022\016"
    "\n\006log_id\030\001 \002(\t\022\013\n\003pwd\030\002 \002(\t\022\r\n\005email\030\003 \002"
    "(\t", 82);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "iegad_app_svr_msg.proto", &protobuf_RegisterTypes);
  setup_msg::default_instance_ = new setup_msg();
  setup_msg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_iegad_5fapp_5fsvr_5fmsg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_iegad_5fapp_5fsvr_5fmsg_2eproto {
  StaticDescriptorInitializer_iegad_5fapp_5fsvr_5fmsg_2eproto() {
    protobuf_AddDesc_iegad_5fapp_5fsvr_5fmsg_2eproto();
  }
} static_descriptor_initializer_iegad_5fapp_5fsvr_5fmsg_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int setup_msg::kLogIdFieldNumber;
const int setup_msg::kPwdFieldNumber;
const int setup_msg::kEmailFieldNumber;
#endif  // !_MSC_VER

setup_msg::setup_msg()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:setup_msg)
}

void setup_msg::InitAsDefaultInstance() {
}

setup_msg::setup_msg(const setup_msg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:setup_msg)
}

void setup_msg::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  log_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pwd_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  email_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

setup_msg::~setup_msg() {
  // @@protoc_insertion_point(destructor:setup_msg)
  SharedDtor();
}

void setup_msg::SharedDtor() {
  if (log_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete log_id_;
  }
  if (pwd_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete pwd_;
  }
  if (email_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete email_;
  }
  if (this != default_instance_) {
  }
}

void setup_msg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* setup_msg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return setup_msg_descriptor_;
}

const setup_msg& setup_msg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_iegad_5fapp_5fsvr_5fmsg_2eproto();
  return *default_instance_;
}

setup_msg* setup_msg::default_instance_ = NULL;

setup_msg* setup_msg::New() const {
  return new setup_msg;
}

void setup_msg::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_log_id()) {
      if (log_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        log_id_->clear();
      }
    }
    if (has_pwd()) {
      if (pwd_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        pwd_->clear();
      }
    }
    if (has_email()) {
      if (email_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        email_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool setup_msg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:setup_msg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string log_id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_log_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->log_id().data(), this->log_id().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "log_id");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_pwd;
        break;
      }

      // required string pwd = 2;
      case 2: {
        if (tag == 18) {
         parse_pwd:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_pwd()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->pwd().data(), this->pwd().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "pwd");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_email;
        break;
      }

      // required string email = 3;
      case 3: {
        if (tag == 26) {
         parse_email:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_email()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->email().data(), this->email().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "email");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:setup_msg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:setup_msg)
  return false;
#undef DO_
}

void setup_msg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:setup_msg)
  // required string log_id = 1;
  if (has_log_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->log_id().data(), this->log_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "log_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->log_id(), output);
  }

  // required string pwd = 2;
  if (has_pwd()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->pwd().data(), this->pwd().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pwd");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->pwd(), output);
  }

  // required string email = 3;
  if (has_email()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->email().data(), this->email().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "email");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->email(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:setup_msg)
}

::google::protobuf::uint8* setup_msg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:setup_msg)
  // required string log_id = 1;
  if (has_log_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->log_id().data(), this->log_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "log_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->log_id(), target);
  }

  // required string pwd = 2;
  if (has_pwd()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->pwd().data(), this->pwd().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "pwd");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->pwd(), target);
  }

  // required string email = 3;
  if (has_email()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->email().data(), this->email().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "email");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->email(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:setup_msg)
  return target;
}

int setup_msg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string log_id = 1;
    if (has_log_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->log_id());
    }

    // required string pwd = 2;
    if (has_pwd()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->pwd());
    }

    // required string email = 3;
    if (has_email()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->email());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void setup_msg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const setup_msg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const setup_msg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void setup_msg::MergeFrom(const setup_msg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_log_id()) {
      set_log_id(from.log_id());
    }
    if (from.has_pwd()) {
      set_pwd(from.pwd());
    }
    if (from.has_email()) {
      set_email(from.email());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void setup_msg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void setup_msg::CopyFrom(const setup_msg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool setup_msg::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void setup_msg::Swap(setup_msg* other) {
  if (other != this) {
    std::swap(log_id_, other->log_id_);
    std::swap(pwd_, other->pwd_);
    std::swap(email_, other->email_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata setup_msg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = setup_msg_descriptor_;
  metadata.reflection = setup_msg_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
