// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_basic.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msg_basic.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace iegad {
namespace net {

namespace {

const ::google::protobuf::Descriptor* tcp_msg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  tcp_msg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_msg_5fbasic_2eproto() {
  protobuf_AddDesc_msg_5fbasic_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msg_basic.proto");
  GOOGLE_CHECK(file != NULL);
  tcp_msg_descriptor_ = file->message_type(0);
  static const int tcp_msg_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tcp_msg, msg_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tcp_msg, msg_flag_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tcp_msg, msg_bdstr_),
  };
  tcp_msg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      tcp_msg_descriptor_,
      tcp_msg::default_instance_,
      tcp_msg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tcp_msg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tcp_msg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(tcp_msg));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msg_5fbasic_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    tcp_msg_descriptor_, &tcp_msg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msg_5fbasic_2eproto() {
  delete tcp_msg::default_instance_;
  delete tcp_msg_reflection_;
}

void protobuf_AddDesc_msg_5fbasic_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017msg_basic.proto\022\tiegad.net\"@\n\007tcp_msg\022"
    "\020\n\010msg_type\030\001 \002(\005\022\020\n\010msg_flag\030\002 \002(\005\022\021\n\tm"
    "sg_bdstr\030\003 \002(\t", 94);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msg_basic.proto", &protobuf_RegisterTypes);
  tcp_msg::default_instance_ = new tcp_msg();
  tcp_msg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msg_5fbasic_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msg_5fbasic_2eproto {
  StaticDescriptorInitializer_msg_5fbasic_2eproto() {
    protobuf_AddDesc_msg_5fbasic_2eproto();
  }
} static_descriptor_initializer_msg_5fbasic_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int tcp_msg::kMsgTypeFieldNumber;
const int tcp_msg::kMsgFlagFieldNumber;
const int tcp_msg::kMsgBdstrFieldNumber;
#endif  // !_MSC_VER

tcp_msg::tcp_msg()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:iegad.net.tcp_msg)
}

void tcp_msg::InitAsDefaultInstance() {
}

tcp_msg::tcp_msg(const tcp_msg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:iegad.net.tcp_msg)
}

void tcp_msg::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  msg_type_ = 0;
  msg_flag_ = 0;
  msg_bdstr_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

tcp_msg::~tcp_msg() {
  // @@protoc_insertion_point(destructor:iegad.net.tcp_msg)
  SharedDtor();
}

void tcp_msg::SharedDtor() {
  if (msg_bdstr_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete msg_bdstr_;
  }
  if (this != default_instance_) {
  }
}

void tcp_msg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* tcp_msg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return tcp_msg_descriptor_;
}

const tcp_msg& tcp_msg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_5fbasic_2eproto();
  return *default_instance_;
}

tcp_msg* tcp_msg::default_instance_ = NULL;

tcp_msg* tcp_msg::New() const {
  return new tcp_msg;
}

void tcp_msg::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<tcp_msg*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(msg_type_, msg_flag_);
    if (has_msg_bdstr()) {
      if (msg_bdstr_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        msg_bdstr_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool tcp_msg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:iegad.net.tcp_msg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 msg_type = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &msg_type_)));
          set_has_msg_type();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_msg_flag;
        break;
      }

      // required int32 msg_flag = 2;
      case 2: {
        if (tag == 16) {
         parse_msg_flag:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &msg_flag_)));
          set_has_msg_flag();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_msg_bdstr;
        break;
      }

      // required string msg_bdstr = 3;
      case 3: {
        if (tag == 26) {
         parse_msg_bdstr:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg_bdstr()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->msg_bdstr().data(), this->msg_bdstr().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "msg_bdstr");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:iegad.net.tcp_msg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:iegad.net.tcp_msg)
  return false;
#undef DO_
}

void tcp_msg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:iegad.net.tcp_msg)
  // required int32 msg_type = 1;
  if (has_msg_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->msg_type(), output);
  }

  // required int32 msg_flag = 2;
  if (has_msg_flag()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->msg_flag(), output);
  }

  // required string msg_bdstr = 3;
  if (has_msg_bdstr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msg_bdstr().data(), this->msg_bdstr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "msg_bdstr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->msg_bdstr(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:iegad.net.tcp_msg)
}

::google::protobuf::uint8* tcp_msg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:iegad.net.tcp_msg)
  // required int32 msg_type = 1;
  if (has_msg_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->msg_type(), target);
  }

  // required int32 msg_flag = 2;
  if (has_msg_flag()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->msg_flag(), target);
  }

  // required string msg_bdstr = 3;
  if (has_msg_bdstr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msg_bdstr().data(), this->msg_bdstr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "msg_bdstr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->msg_bdstr(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:iegad.net.tcp_msg)
  return target;
}

int tcp_msg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 msg_type = 1;
    if (has_msg_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->msg_type());
    }

    // required int32 msg_flag = 2;
    if (has_msg_flag()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->msg_flag());
    }

    // required string msg_bdstr = 3;
    if (has_msg_bdstr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->msg_bdstr());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void tcp_msg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const tcp_msg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const tcp_msg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void tcp_msg::MergeFrom(const tcp_msg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msg_type()) {
      set_msg_type(from.msg_type());
    }
    if (from.has_msg_flag()) {
      set_msg_flag(from.msg_flag());
    }
    if (from.has_msg_bdstr()) {
      set_msg_bdstr(from.msg_bdstr());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void tcp_msg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void tcp_msg::CopyFrom(const tcp_msg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool tcp_msg::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void tcp_msg::Swap(tcp_msg* other) {
  if (other != this) {
    std::swap(msg_type_, other->msg_type_);
    std::swap(msg_flag_, other->msg_flag_);
    std::swap(msg_bdstr_, other->msg_bdstr_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata tcp_msg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = tcp_msg_descriptor_;
  metadata.reflection = tcp_msg_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace net
}  // namespace iegad

// @@protoc_insertion_point(global_scope)
