/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Astroboy_CONSTANTS_H
#define Astroboy_CONSTANTS_H

#include "Astroboy_types.h"

namespace iegad { namespace thrift_ex {

class AstroboyConstants {
 public:
  AstroboyConstants();

};

extern const AstroboyConstants g_Astroboy_constants;

}} // namespace

#endif
