/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef testing_CONSTANTS_H
#define testing_CONSTANTS_H

#include "testing_types.h"

namespace test {

class testingConstants {
 public:
  testingConstants();

};

extern const testingConstants g_testing_constants;

} // namespace

#endif
