/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef onepc.Data_CONSTANTS_H
#define onepc.Data_CONSTANTS_H

#include "onepc.Data_types.h"

namespace iegad { namespace onepc { namespace data {

class onepc.DataConstants {
 public:
  onepc.DataConstants();

};

extern const onepc.DataConstants g_onepc.Data_constants;

}}} // namespace

#endif
